CREATE TABLE IF NOT EXISTS users
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(120) NOT NULL,

    email VARCHAR(120) UNIQUE NOT NULL,

    phone VARCHAR(20) UNIQUE NOT NULL,

    user_name VARCHAR(50) UNIQUE NOT NULL,

    password TEXT NOT NULL,

    role VARCHAR(30) NOT NULL DEFAULT 'USER',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);