import { Router } from "express";
import * as controller from "../controllers/index.controller";
import { authenticate } from "../middleware/auth.middleware";
import { validate } from "../middleware/validate.middleware";
import { createOrderValidator, updateOrderValidator } from "../validators/index.validator";
const router=Router();
router.use(authenticate);
router.post("/",validate(createOrderValidator),controller.createOrder); router.get("/",controller.getOrders); router.get("/:id",controller.getOrder);
router.put("/:id",validate(updateOrderValidator),controller.updateOrder); router.patch("/:id/cancel",controller.cancelOrder); router.patch("/:id/payment-status",controller.updatePaymentStatus);
export default router;
